//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.esd.org.uk/inventory")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.esd.org.uk/inventory", IsNullable = false)]
public partial class Inventory
{
    [XmlNamespaceDeclarations]
    public XmlSerializerNamespaces _xsns;

    public Inventory()
    {
        _xsns = new XmlSerializerNamespaces(
            new XmlQualifiedName[] { new XmlQualifiedName("inv", "http://schemas.esd.org.uk/inventory"),  
            new XmlQualifiedName("conformsTo", "http://schemas.esd.org.uk/inventory/inventory.xsd"), 
            
            });
    }
    /// <remarks/>
    [XmlNamespaceDeclarations]
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Identifier;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 1)]
    public string Creator;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public InventoryMetadata Metadata;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Dataset", IsNullable = false)]
    public InventoryDataset[] Datasets;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime Modified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Language;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.esd.org.uk/inventory")]
public partial class InventoryMetadata
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 0)]
    public string Publisher;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Title;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Description;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Spatial", DataType = "anyURI", IsNullable = false)]
    public string[] Coverage;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.esd.org.uk/inventory")]
public partial class InventoryDataset
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Identifier;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Title;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Description;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 3)]
    public string Rights;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Protected;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string ProtectedText;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string Context;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public string RightsHolder;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public string ChargeURL;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 9)]
    public System.DateTime CommittmentDate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CommittmentDateSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public string RelationType;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Relations", Order = 11)]
    public InventoryDatasetRelations[] Relations;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 12)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Subject", typeof(InventoryDatasetSubjectsSubject), IsNullable = false)]
    public InventoryDatasetSubjectsSubject[] Subjects;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 13)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Resource", IsNullable = false)]
    public InventoryDatasetResource[] Resources;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime Modified;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ModifiedSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Active;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.esd.org.uk/inventory")]
public partial class InventoryDatasetRelations
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 0)]
    public string Relation;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.esd.org.uk/inventory")]
public partial class InventoryDatasetSubjectsSubject
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Service;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Function;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Scheme;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.esd.org.uk/inventory")]
public partial class InventoryDatasetResource
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Identifier;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Title;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Description;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public InventoryDatasetResourceCoverage Coverage;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public InventoryDatasetResourceRenditions Renditions;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime Modified;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ModifiedSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Active;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Language;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.esd.org.uk/inventory")]
public partial class InventoryDatasetResourceCoverage
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Spatial", DataType = "anyURI", Order = 0)]
    public string[] Spatial;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime TemporalFrom;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TemporalFromSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime TemporalTo;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TemporalToSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.esd.org.uk/inventory")]
public partial class InventoryDatasetResourceRenditions
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public InventoryDatasetResourceRenditionsRendition Rendition;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.esd.org.uk/inventory")]
public partial class InventoryDatasetResourceRenditionsRendition
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 0)]
    public string Identifier;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string MimeType;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Title;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string Description;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Availability;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ConformsTo", Order = 5)]
    public string[] ConformsTo;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Active;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime Modified;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ModifiedSpecified;
}
